live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#FF8C00"
text = "CellBackground"

[colors.normal]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#828997"
yellow = "#e5c07b"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style = "Block"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0000c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000-"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000\\"
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0000h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000j"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000x"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = true
option_as_alt = "Both"

[window.dimensions]
columns = 110
lines = 48

[window.padding]
x = 0
y = 0
