#! /usr/bin/env bash

echo "This file should be sourced..."
echo ''

export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_RUNTIME_DIR=${HOME}/tmp/xdg_runtime

while read -r env; do
  echo "Sourcing $env"
  source "${env}"
done < <(find . -name env.zsh)
echo ''

make all
source $XDG_CONFIG_HOME/zsh/.zshrc