#!/usr/bin/env bash

export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_RUNTIME_DIR=${HOME}/tmp/xdg_runtime

while read -r env; do
  echo "Sourcing $env"
  source "${env}"
done < <(find . -name env.zsh)
echo ''

UNAME=`uname`
if test ! "$(command -v brew)"; then
  echo "Setting up Homebrew..."
  echo ''
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  while read -r brw; do
    echo "${brw}"
  done < <(brew update)
  echo ''
fi

if [ "$UNAME" = "Linux" ]; then
  /bin/bash install-linux.sh
  echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ${XDG_CONFIG_HOME}/zsh/local.zsh
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

  brew bundle --file=linux.brewfile
elif [ "$UNAME" == "Darwin" ]; then
  brew bundle --file=darwin.brewfile
fi

make all
if [ ! -d "${HOME}/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

source $XDG_CONFIG_HOME/zsh/.zshrc