#!/bin/bash

set -e

DOTS=${DOTS:-~/.dots}

. "$DOTS/util/functions.sh"

_config() {
  if [ -n $FISH_VERSION ]; then
    $EDITOR ~/.config/fish/config.fish
  else
    echo "not supported"
  fi
}

_edit() {
  pushd $DOTS
  git pull
  $EDITOR .
}

_update() {
  pushd $DOTS > /dev/null 2> /dev/null
  git pull

  if [ -n $FISH_VERSION ]; then
    exec fish -l $DOTS/fish/scripts/bootstrap.fish
  elif [ -n $nu.home-path ]; then
    echo "nushell coming soon"
  else
    echo "not supported"
  fi

  popd > /dev/null 2> /dev/null
}

_install() {
  case "$2" in
    fish)
      if ! command_exists? fish; then
        echo "${YELLOW}Fish is not installed.${RESET} Please install fish first."
        exit 1
      fi
      exec fish -l ${DOTS}/fish/scripts/bootstrap.fish
      ;;
    nushell)
      fmt_error "$2 is not yet supported."
      exit 1
      ;;
    nix-fish*)
      source ${DOTS}/nix/install.sh


      # if ! command_exists? fish; then
      #   echo "${YELLOW}Fish is not installed.${RESET} Please install fish first."
      #   exit 1
      # fi
      # exec fish -l ${DOTS}/fish/scripts/bootstrap.fish
      ;;
  esac
}

_reload() {
  exec "$SHELL" -l
}

# Show usage
_usage() {
  cat << EOF
Usage: dots {action}
actions:
     edit - open '$DOTS' directory in default $EDITOR
     reload - reload shell
     up,update - update
     install - install for shell
EOF
}

action=$1;

case "${action}" in
  config)   _config;;
  edit)     _edit;;
  reload)   _reload;;
  up)       _update;;
  update)   _update;;
  install)  _install "$@";;

  help)     _usage;;
  --help)   _usage;;
  h)        _usage;;
  *)        _usage;;
esac

exit 0
