#!/bin/bash

set -e

DOTS=${DOTS:-~/.dots}

. "$DOTS/util/functions.sh"

setup_color

_config() {
  if [ -n $FISH_VERSION ]; then
    $EDITOR ~/.config/fish/config.fish
  else
    echo "not supported"
  fi
}

_edit() {
  pushd $DOTS
  git pull
  $EDITOR .
}

_update() {
  pushd $DOTS > /dev/null 2> /dev/null
  git pull

  if [ -n $FISH_VERSION ]; then
    fish $DOTS/fish/scripts/bootstrap.fish
  elif [ -n $nu.home-path ]; then
    echo "nushell"
  else
    echo "not supported"
  fi

  # if test -n "$ZSH_VERSION"; then
  #   PROFILE_SHELL=zsh
  # elif test -n "$BASH_VERSION"; then
  #   PROFILE_SHELL=bash
  # elif test -n "$KSH_VERSION"; then
  #   PROFILE_SHELL=ksh
  # elif test -n "$FCEDIT"; then
  #   PROFILE_SHELL=ksh
  # elif test -n "$PS3"; then
  #   PROFILE_SHELL=unknown
  # else
  #   PROFILE_SHELL=sh
  # fi

  popd > /dev/null 2> /dev/null
}

_reload() {
  exec "$SHELL" -l
}

# Show usage
_usage() {
  cat << EOF
Usage: dots {action}
actions:
     edit - open '$DOTS' directory in default $EDITOR
     reload - reload shell
     up,update - update
EOF
}

action=$1;

case "${action}" in
  config)   _config;;
  edit)     _edit;;
  reload)   _reload;;
  up)       _update;;
  update)   _update;;

  help)     _usage;;
  --help)   _usage;;
  h)        _usage;;
  *)        _usage;;
esac

exit 0
