export ZSH=$HOME/.dots/zsh

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_RUNTIME_DIR=$HOME/tmp/runtime

export EDITOR=vim

export BREWPATH=/usr/local/Cellar

# Path to your oh-my-zsh installation.
# export ZSH=$XDG_CONFIG_HOME/oh-my-zsh/
# export ZSH_CUSTOM=$ZSH/custom/
export ZDOTDIR=$XDG_CONFIG_HOME/zsh/
export ZSH_COMPDUMP=$XDG_DATA_HOME/zsh/zshCompletionDump
export ZSH_CACHE_DIR=$XDG_CACHE_HOME/zsh/